# Generated by Django 2.0.5 on 2018-05-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
    ]
